export const LABEL_TRANSLATIONS = {
  person: {
    "pt-BR": "Pessoa",
    "en-US": "Person",
    "es-ES": "Persona",
    "fr-FR": "Personne",
    "de-DE": "Person",
    "it-IT": "Persona",
  },
  bicycle: {
    "pt-BR": "Bicicleta",
    "en-US": "Bicycle",
    "es-ES": "Bicicleta",
    "fr-FR": "Vélo",
    "de-DE": "Fahrrad",
    "it-IT": "Bicicletta",
  },
  car: {
    "pt-BR": "Carro",
    "en-US": "Car",
    "es-ES": "Coche",
    "fr-FR": "Voiture",
    "de-DE": "Auto",
    "it-IT": "Auto",
  },
  motorcycle: {
    "pt-BR": "Motocicleta",
    "en-US": "Motorcycle",
    "es-ES": "Motocicleta",
    "fr-FR": "Moto",
    "de-DE": "Motorrad",
    "it-IT": "Motocicletta",
  },
  airplane: {
    "pt-BR": "Avião",
    "en-US": "Airplane",
    "es-ES": "Avión",
    "fr-FR": "Avion",
    "de-DE": "Flugzeug",
    "it-IT": "Aereo",
  },
  bus: {
    "pt-BR": "Ônibus",
    "en-US": "Bus",
    "es-ES": "Autobús",
    "fr-FR": "Bus",
    "de-DE": "Bus",
    "it-IT": "Autobus",
  },
  train: {
    "pt-BR": "Trem",
    "en-US": "Train",
    "es-ES": "Tren",
    "fr-FR": "Train",
    "de-DE": "Zug",
    "it-IT": "Treno",
  },
  truck: {
    "pt-BR": "Caminhão",
    "en-US": "Truck",
    "es-ES": "Camión",
    "fr-FR": "Camion",
    "de-DE": "Lastwagen",
    "it-IT": "Camion",
  },
  boat: {
    "pt-BR": "Barco",
    "en-US": "Boat",
    "es-ES": "Barco",
    "fr-FR": "Bateau",
    "de-DE": "Boot",
    "it-IT": "Barca",
  },
  traffic_light: {
    "pt-BR": "Semáforo",
    "en-US": "Traffic Light",
    "es-ES": "Semáforo",
    "fr-FR": "Feu de circulation",
    "de-DE": "Ampel",
    "it-IT": "Semaforo",
  },
  fire_hydrant: {
    "pt-BR": "Hidrante",
    "en-US": "Fire Hydrant",
    "es-ES": "Hidrante",
    "fr-FR": "Borne incendie",
    "de-DE": "Feuerhydrant",
    "it-IT": "Idrante",
  },
  stop_sign: {
    "pt-BR": "Placa de Pare",
    "en-US": "Stop Sign",
    "es-ES": "Señal de stop",
    "fr-FR": "Panneau stop",
    "de-DE": "Stoppschild",
    "it-IT": "Cartello stop",
  },
  parking_meter: {
    "pt-BR": "Parquímetro",
    "en-US": "Parking Meter",
    "es-ES": "Parquímetro",
    "fr-FR": "Parcmètre",
    "de-DE": "Parkuhr",
    "it-IT": "Parcometro",
  },
  bench: {
    "pt-BR": "Banco",
    "en-US": "Bench",
    "es-ES": "Banco",
    "fr-FR": "Banc",
    "de-DE": "Bank",
    "it-IT": "Panchina",
  },
  bird: {
    "pt-BR": "Pássaro",
    "en-US": "Bird",
    "es-ES": "Pájaro",
    "fr-FR": "Oiseau",
    "de-DE": "Vogel",
    "it-IT": "Uccello",
  },
  cat: {
    "pt-BR": "Gato",
    "en-US": "Cat",
    "es-ES": "Gato",
    "fr-FR": "Chat",
    "de-DE": "Katze",
    "it-IT": "Gatto",
  },
  dog: {
    "pt-BR": "Cachorro",
    "en-US": "Dog",
    "es-ES": "Perro",
    "fr-FR": "Chien",
    "de-DE": "Hund",
    "it-IT": "Cane",
  },
  horse: {
    "pt-BR": "Cavalo",
    "en-US": "Horse",
    "es-ES": "Caballo",
    "fr-FR": "Cheval",
    "de-DE": "Pferd",
    "it-IT": "Cavallo",
  },
  sheep: {
    "pt-BR": "Ovelha",
    "en-US": "Sheep",
    "es-ES": "Oveja",
    "fr-FR": "Mouton",
    "de-DE": "Schaf",
    "it-IT": "Pecora",
  },
  cow: {
    "pt-BR": "Vaca",
    "en-US": "Cow",
    "es-ES": "Vaca",
    "fr-FR": "Vache",
    "de-DE": "Kuh",
    "it-IT": "Mucca",
  },
  elephant: {
    "pt-BR": "Elefante",
    "en-US": "Elephant",
    "es-ES": "Elefante",
    "fr-FR": "Éléphant",
    "de-DE": "Elefant",
    "it-IT": "Elefante",
  },
  bear: {
    "pt-BR": "Urso",
    "en-US": "Bear",
    "es-ES": "Oso",
    "fr-FR": "Ours",
    "de-DE": "Bär",
    "it-IT": "Orso",
  },
  zebra: {
    "pt-BR": "Zebra",
    "en-US": "Zebra",
    "es-ES": "Cebra",
    "fr-FR": "Zèbre",
    "de-DE": "Zebra",
    "it-IT": "Zebra",
  },
  giraffe: {
    "pt-BR": "Girafa",
    "en-US": "Giraffe",
    "es-ES": "Jirafa",
    "fr-FR": "Girafe",
    "de-DE": "Giraffe",
    "it-IT": "Giraffa",
  },
  backpack: {
    "pt-BR": "Mochila",
    "en-US": "Backpack",
    "es-ES": "Mochila",
    "fr-FR": "Sac à dos",
    "de-DE": "Rucksack",
    "it-IT": "Zaino",
  },
  umbrella: {
    "pt-BR": "Guarda-chuva",
    "en-US": "Umbrella",
    "es-ES": "Paraguas",
    "fr-FR": "Parapluie",
    "de-DE": "Regenschirm",
    "it-IT": "Ombrello",
  },
  handbag: {
    "pt-BR": "Bolsa",
    "en-US": "Handbag",
    "es-ES": "Bolso",
    "fr-FR": "Sac à main",
    "de-DE": "Handtasche",
    "it-IT": "Borsa",
  },
  tie: {
    "pt-BR": "Gravata",
    "en-US": "Tie",
    "es-ES": "Corbata",
    "fr-FR": "Cravate",
    "de-DE": "Krawatte",
    "it-IT": "Cravatta",
  },
  suitcase: {
    "pt-BR": "Mala",
    "en-US": "Suitcase",
    "es-ES": "Maleta",
    "fr-FR": "Valise",
    "de-DE": "Koffer",
    "it-IT": "Valigia",
  },
  frisbee: {
    "pt-BR": "Frisbee",
    "en-US": "Frisbee",
    "es-ES": "Frisbi",
    "fr-FR": "Frisbee",
    "de-DE": "Frisbee",
    "it-IT": "Frisbee",
  },
  skis: {
    "pt-BR": "Esquis",
    "en-US": "Skis",
    "es-ES": "Esquís",
    "fr-FR": "Skis",
    "de-DE": "Skier",
    "it-IT": "Sci",
  },
  snowboard: {
    "pt-BR": "Snowboard",
    "en-US": "Snowboard",
    "es-ES": "Snowboard",
    "fr-FR": "Snowboard",
    "de-DE": "Snowboard",
    "it-IT": "Snowboard",
  },
  sports_ball: {
    "pt-BR": "Bola de Esporte",
    "en-US": "Sports Ball",
    "es-ES": "Pelota",
    "fr-FR": "Balle",
    "de-DE": "Sportball",
    "it-IT": "Pallone",
  },
  kite: {
    "pt-BR": "Pipa",
    "en-US": "Kite",
    "es-ES": "Cometa",
    "fr-FR": "Cerf-volant",
    "de-DE": "Drachen",
    "it-IT": "Aquilone",
  },
  baseball_bat: {
    "pt-BR": "Taco de Beisebol",
    "en-US": "Baseball Bat",
    "es-ES": "Bate de béisbol",
    "fr-FR": "Batte de baseball",
    "de-DE": "Baseballschläger",
    "it-IT": "Mazza da baseball",
  },
  baseball_glove: {
    "pt-BR": "Luva de Beisebol",
    "en-US": "Baseball Glove",
    "es-ES": "Guante",
    "fr-FR": "Gant",
    "de-DE": "Handschuh",
    "it-IT": "Guanto",
  },
  skateboard: {
    "pt-BR": "Skate",
    "en-US": "Skateboard",
    "es-ES": "Patineta",
    "fr-FR": "Skateboard",
    "de-DE": "Skateboard",
    "it-IT": "Skateboard",
  },
  surfboard: {
    "pt-BR": "Prancha de Surfe",
    "en-US": "Surfboard",
    "es-ES": "Tabla de surf",
    "fr-FR": "Planche de surf",
    "de-DE": "Surfbrett",
    "it-IT": "Tavola da surf",
  },
  tennis_racket: {
    "pt-BR": "Raquete de Tênis",
    "en-US": "Tennis Racket",
    "es-ES": "Raqueta",
    "fr-FR": "Raquette",
    "de-DE": "Tennisschläger",
    "it-IT": "Racchetta",
  },
  bottle: {
    "pt-BR": "Garrafa",
    "en-US": "Bottle",
    "es-ES": "Botella",
    "fr-FR": "Bouteille",
    "de-DE": "Flasche",
    "it-IT": "Bottiglia",
  },
  wine_glass: {
    "pt-BR": "Taça de Vinho",
    "en-US": "Wine Glass",
    "es-ES": "Copa de vino",
    "fr-FR": "Verre à vin",
    "de-DE": "Weinglas",
    "it-IT": "Calice",
  },
  cup: {
    "pt-BR": "Copo",
    "en-US": "Cup",
    "es-ES": "Taza",
    "fr-FR": "Tasse",
    "de-DE": "Tasse",
    "it-IT": "Tazza",
  },
  fork: {
    "pt-BR": "Garfo",
    "en-US": "Fork",
    "es-ES": "Tenedor",
    "fr-FR": "Fourchette",
    "de-DE": "Gabel",
    "it-IT": "Forchetta",
  },
  knife: {
    "pt-BR": "Faca",
    "en-US": "Knife",
    "es-ES": "Cuchillo",
    "fr-FR": "Couteau",
    "de-DE": "Messer",
    "it-IT": "Coltello",
  },
  spoon: {
    "pt-BR": "Colher",
    "en-US": "Spoon",
    "es-ES": "Cuchara",
    "fr-FR": "Cuillère",
    "de-DE": "Löffel",
    "it-IT": "Cucchiaio",
  },
  bowl: {
    "pt-BR": "Tigela",
    "en-US": "Bowl",
    "es-ES": "Tazón",
    "fr-FR": "Bol",
    "de-DE": "Schüssel",
    "it-IT": "Ciotola",
  },
  banana: {
    "pt-BR": "Banana",
    "en-US": "Banana",
    "es-ES": "Banana",
    "fr-FR": "Banane",
    "de-DE": "Banane",
    "it-IT": "Banana",
  },
  apple: {
    "pt-BR": "Maçã",
    "en-US": "Apple",
    "es-ES": "Manzana",
    "fr-FR": "Pomme",
    "de-DE": "Apfel",
    "it-IT": "Mela",
  },
  sandwich: {
    "pt-BR": "Sanduíche",
    "en-US": "Sandwich",
    "es-ES": "Sándwich",
    "fr-FR": "Sandwich",
    "de-DE": "Sandwich",
    "it-IT": "Panino",
  },
  orange: {
    "pt-BR": "Laranja",
    "en-US": "Orange",
    "es-ES": "Naranja",
    "fr-FR": "Orange",
    "de-DE": "Orange",
    "it-IT": "Arancia",
  },
  broccoli: {
    "pt-BR": "Brócolis",
    "en-US": "Broccoli",
    "es-ES": "Brócoli",
    "fr-FR": "Brocoli",
    "de-DE": "Brokkoli",
    "it-IT": "Broccoli",
  },
  carrot: {
    "pt-BR": "Cenoura",
    "en-US": "Carrot",
    "es-ES": "Zanahoria",
    "fr-FR": "Carotte",
    "de-DE": "Karotte",
    "it-IT": "Carota",
  },
  hot_dog: {
    "pt-BR": "Cachorro-quente",
    "en-US": "Hot Dog",
    "es-ES": "Perro caliente",
    "fr-FR": "Hot-dog",
    "de-DE": "Hotdog",
    "it-IT": "Hot dog",
  },
  pizza: {
    "pt-BR": "Pizza",
    "en-US": "Pizza",
    "es-ES": "Pizza",
    "fr-FR": "Pizza",
    "de-DE": "Pizza",
    "it-IT": "Pizza",
  },
  donut: {
    "pt-BR": "Rosquinha",
    "en-US": "Donut",
    "es-ES": "Dona",
    "fr-FR": "Donut",
    "de-DE": "Donut",
    "it-IT": "Ciambella",
  },
  cake: {
    "pt-BR": "Bolo",
    "en-US": "Cake",
    "es-ES": "Pastel",
    "fr-FR": "Gâteau",
    "de-DE": "Kuchen",
    "it-IT": "Torta",
  },
  chair: {
    "pt-BR": "Cadeira",
    "en-US": "Chair",
    "es-ES": "Silla",
    "fr-FR": "Chaise",
    "de-DE": "Stuhl",
    "it-IT": "Sedia",
  },
  couch: {
    "pt-BR": "Sofá",
    "en-US": "Couch",
    "es-ES": "Sofá",
    "fr-FR": "Canapé",
    "de-DE": "Sofa",
    "it-IT": "Divano",
  },
  potted_plant: {
    "pt-BR": "Planta em Vaso",
    "en-US": "Potted Plant",
    "es-ES": "Planta en maceta",
    "fr-FR": "Plante en pot",
    "de-DE": "Topfpflanze",
    "it-IT": "Pianta in vaso",
  },
  bed: {
    "pt-BR": "Cama",
    "en-US": "Bed",
    "es-ES": "Cama",
    "fr-FR": "Lit",
    "de-DE": "Bett",
    "it-IT": "Letto",
  },
  dining_table: {
    "pt-BR": "Mesa de Jantar",
    "en-US": "Dining Table",
    "es-ES": "Mesa de comedor",
    "fr-FR": "Table à manger",
    "de-DE": "Esstisch",
    "it-IT": "Tavolo da pranzo",
  },
  toilet: {
    "pt-BR": "Vaso Sanitário",
    "en-US": "Toilet",
    "es-ES": "Inodoro",
    "fr-FR": "Toilette",
    "de-DE": "Toilette",
    "it-IT": "Gabinetto",
  },
  tv: {
    "pt-BR": "TV",
    "en-US": "TV",
    "es-ES": "Televisor",
    "fr-FR": "Télévision",
    "de-DE": "Fernseher",
    "it-IT": "Televisione",
  },
  laptop: {
    "pt-BR": "Laptop",
    "en-US": "Laptop",
    "es-ES": "Portátil",
    "fr-FR": "Ordinateur portable",
    "de-DE": "Laptop",
    "it-IT": "Laptop",
  },
  mouse: {
    "pt-BR": "Mouse",
    "en-US": "Mouse",
    "es-ES": "Ratón",
    "fr-FR": "Souris",
    "de-DE": "Maus",
    "it-IT": "Mouse",
  },
  remote: {
    "pt-BR": "Controle Remoto",
    "en-US": "Remote",
    "es-ES": "Control remoto",
    "fr-FR": "Télécommande",
    "de-DE": "Fernbedienung",
    "it-IT": "Telecomando",
  },
  keyboard: {
    "pt-BR": "Teclado",
    "en-US": "Keyboard",
    "es-ES": "Teclado",
    "fr-FR": "Clavier",
    "de-DE": "Tastatur",
    "it-IT": "Tastiera",
  },
  cell_phone: {
    "pt-BR": "Celular",
    "en-US": "Cell Phone",
    "es-ES": "Teléfono",
    "fr-FR": "Téléphone",
    "de-DE": "Handy",
    "it-IT": "Telefono",
  },
  microwave: {
    "pt-BR": "Micro-ondas",
    "en-US": "Microwave",
    "es-ES": "Microondas",
    "fr-FR": "Micro-onde",
    "de-DE": "Mikrowelle",
    "it-IT": "Microonde",
  },
  oven: {
    "pt-BR": "Forno",
    "en-US": "Oven",
    "es-ES": "Horno",
    "fr-FR": "Four",
    "de-DE": "Ofen",
    "it-IT": "Forno",
  },
  toaster: {
    "pt-BR": "Torradeira",
    "en-US": "Toaster",
    "es-ES": "Tostadora",
    "fr-FR": "Grille-pain",
    "de-DE": "Toaster",
    "it-IT": "Tostapane",
  },
  sink: {
    "pt-BR": "Pia",
    "en-US": "Sink",
    "es-ES": "Lavabo",
    "fr-FR": "Évier",
    "de-DE": "Spüle",
    "it-IT": "Lavandino",
  },
  refrigerator: {
    "pt-BR": "Geladeira",
    "en-US": "Refrigerator",
    "es-ES": "Refrigerador",
    "fr-FR": "Réfrigérateur",
    "de-DE": "Kühlschrank",
    "it-IT": "Frigorifero",
  },
  book: {
    "pt-BR": "Livro",
    "en-US": "Book",
    "es-ES": "Libro",
    "fr-FR": "Livre",
    "de-DE": "Buch",
    "it-IT": "Libro",
  },
  clock: {
    "pt-BR": "Relógio",
    "en-US": "Clock",
    "es-ES": "Reloj",
    "fr-FR": "Horloge",
    "de-DE": "Uhr",
    "it-IT": "Orologio",
  },
  vase: {
    "pt-BR": "Vaso",
    "en-US": "Vase",
    "es-ES": "Jarrón",
    "fr-FR": "Vase",
    "de-DE": "Vase",
    "it-IT": "Vaso",
  },
  scissors: {
    "pt-BR": "Tesoura",
    "en-US": "Scissors",
    "es-ES": "Tijeras",
    "fr-FR": "Ciseaux",
    "de-DE": "Schere",
    "it-IT": "Forbici",
  },
  teddy_bear: {
    "pt-BR": "Urso de Pelúcia",
    "en-US": "Teddy Bear",
    "es-ES": "Osito",
    "fr-FR": "Ourson",
    "de-DE": "Teddybär",
    "it-IT": "Orsetto",
  },
  hair_drier: {
    "pt-BR": "Secador",
    "en-US": "Hair Dryer",
    "es-ES": "Secador",
    "fr-FR": "Sèche-cheveux",
    "de-DE": "Haartrockner",
    "it-IT": "Asciugacapelli",
  },
  toothbrush: {
    "pt-BR": "Escova de Dente",
    "en-US": "Toothbrush",
    "es-ES": "Cepillo de dientes",
    "fr-FR": "Brosse à dents",
    "de-DE": "Zahnbürste",
    "it-IT": "Spazzolino",
  },
};
